language: node_js
node_js: stable

install:
  - npm install

jobs:
  include:
    - stage: GitHubPages
      script:
        - npm run build
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        keep_history: true
        local_dir: ./public
        fqdn: blog.chensenran.top
