name: Deploy # workflow name

on:
  [push] # 触发事件

jobs:
  build: # job1 id
    runs-on: ubuntu-latest # 运行环境为最新版 Ubuntu
    name: A job to deploy blog.
    steps:
      - name: Checkout # 获取源码
        uses: actions/checkout@master

      - name: Install Dependencies
        run: npm install # 安装 node modules 相关依赖

      - name: Deploy
        id: deploy
        uses: sma11black/hexo-action@v1.0.0
        with:
          deploy_key: ${{ secrets.ACCESS_TOKEN }}
